### ISSUE TITLE
Go: tipのテストが失敗する

### ISSUE THREAD

**Issue by uyorum** [uyorum/go-skkserv-google#2]
[Job #19.2 - uyorum/go-skkserv-google - Travis CI](https://travis-ci.org/uyorum/go-skkserv-google/jobs/203125660)

```
=== RUN   TestRequest
--- FAIL: TestRequest (0.10s)
	skkserv-google_test.go:82: Failed to connect to skkserv
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64cdc5]

goroutine 15 [running]:
testing.tRunner.func1(0xc42007d6c0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:624 +0x264
panic(0x6947c0, 0x8489d0)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25a
github.com/uyorum/go-skkserv-google.TestRequest(0xc42007d6c0)
	/home/travis/gopath/src/github.com/uyorum/go-skkserv-google/skkserv-google_test.go:84 +0x215
testing.tRunner(0xc42007d6c0, 0x6f46d0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:659 +0x98
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:701 +0x2da
exit status 2
FAIL	github.com/uyorum/go-skkserv-google	0.130s
make: *** [test] Error 1
```

**Comment by uyorum** [comment]
ポートをListenするまでに時間がかかっていて直後の`net.Dial`に失敗していた模様
`err != nil`だった場合にリトライするようにした
[skkservパッケージを自前のパッケージに置き換える by uyorum · Pull Request #1 · uyorum/go-skkserv-google](https://github.com/uyorum/go-skkserv-google/pull/1) でついでに修正
